#!/bin/bash
echo -e '\e[5;7;31mPlease update your build of TMWA, then use ./run-all\e[m' >& 2
echo -e 'Or if you want output in separate TTYs, cd login then tmwa-login' >& 2
sleep 10
cd login &&
exec login-server

