#!/bin/bash
echo -e '\e[5;7;31mPlease update your build of TMWA, then use ./run-all\e[m' >& 2
echo -e 'Or if you want output in separate TTYs, cd world/map then tmwa-map' >& 2
sleep 10
cd world/map &&
exec map-server

