#!/bin/bash
SELF=$(realpath $(which "$0"))
cd "$(dirname "$SELF")"

trap 'kill %1 %2 %3' SIGHUP SIGINT SIGQUIT SIGABRT SIGTERM
( cd login && tmwa-login ) &
( cd world && tmwa-char ) &
( cd world/map && tmwa-map ) &

wait
