#!/bin/sh
# Copy or symlink this into your .git/hooks directory.
# E.g., from the top:
#       ln -s ../../git/hooks/post-merge .git/hooks
# or    cp git/hooks/post-merge .git/hooks

# If we have local changes in the submodule, rebase them
git submodule update --rebase

# WARNING: to people with push access.
# it is essential that changes to the client data be pushed before changes to server data
# Also, you may find this useful: (you should always clone using the git:// url)
# git config --global url.git@gitorious.org:.pushInsteadOf git://gitorious.org
